name: Java CI

on:
  push:
    branches: [ main ] # or any branch you want

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.find.outputs.files }}
    steps:
      - uses: actions/checkout@v3
      - name: Identify changed Java files
        id: find
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.java$' || true)

          if [ -z "$CHANGED_FILES" ]; then
            echo "files=" >> $GITHUB_OUTPUT
          else
            echo "files=$CHANGED_FILES" >> $GITHUB_OUTPUT
            echo "Changed files: $CHANGED_FILES"
          fi

  codeql-analysis:
    needs: detect-changes
    if: needs.detect-changes.outputs.files != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # ✅ Setup & Init CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java
      # ✅ Perform CodeQL Analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  compile:
    needs: [detect-changes, codeql-analysis]
    if: needs.detect-changes.outputs.files != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Compile changed files
        run: |
          IFS=$'\n'
          for FILE in ${{ needs.detect-changes.outputs.files }}
          do
            echo "Compiling $FILE..."
            javac "$FILE"
          done

  run:
    needs: compile
    if: needs.detect-changes.outputs.files != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run compiled files
        run: |
          IFS=$'\n'
          for FILE in ${{ needs.detect-changes.outputs.files }}
          do
            CLASS_NAME=$(basename "$FILE" .java)
            echo "Running $CLASS_NAME..."
            java "$CLASS_NAME"
          done
