name: Java Practice CI

on:
  push:
    branches: [ main ] # or any branch you want

jobs:
  changed_files:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for accurate diff
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: '**/*.java' # only java files
      - name: List changed files
        run: |
          if [ -z "${{ steps.changed-files.outputs.all_changed_files }}" ]; then
            echo "No Java files changed."
          else
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              echo "$file was changed."
            done
          fi

  codeql-analysis:
    needs: changed_files
    if: needs.changed_files.outputs.files != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # ✅ Setup Java
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # ✅ Init CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java
      # ✅ Perform the Analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3


  compile:
    needs: [changed_files, codeql-analysis]
    if: needs.changed_files.outputs.files != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Compile changed files
        run: |
          IFS=$'\n'
          for FILE in ${{ needs.changed_files.outputs.files }}
          do
            echo "Compiling $FILE..."
            javac "$FILE"
          done

  run:
    needs: [compile, codeql-analysis]
    if: needs.changed_files.outputs.files != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run compiled files
        run: |
          IFS=$'\n'
          for FILE in ${{ needs.changed_files.outputs.files }}
          do
            CLASS_NAME=$(basename "$FILE" .java)
            echo "Running $CLASS_NAME..."
            java "$CLASS_NAME"
          done
