name: Java CI

on:
  push:
    branches: [ main ] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Find changed Java files
        id: changed_files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.java$' || true)

          if [ -z "$CHANGED_FILES" ]; then
            echo "No Java files changed."
            echo "files=" >> $GITHUB_OUTPUT
          else
            echo "Changed Java files: $CHANGED_FILES"
            echo "files=$CHANGED_FILES" >> $GITHUB_OUTPUT
          fi

      - name: Compile
        if: steps.changed_files.outputs.files != ''
        run: |
          IFS=$'\n'
          for FILE in ${{ steps.changed_files.outputs.files }}
          do
            echo "Compiling $FILE..."
            javac "$FILE"
          done

  
      - name: Run
        if: steps.changed_files.outputs.files != ''
        run: |
          IFS=$'\n'
          for FILE in ${{ steps.changed_files.outputs.files }}
          do
            CLASS_NAME=$(basename "$FILE" .java)
            echo "Running $CLASS_NAME..."
            java "$CLASS_NAME"
          done
